"""Event envelope helpers.

``new_event`` constructs a fresh ``Event`` pb with ``run_id``, ``sequence``
and ``emitted_at`` populated. ``emit`` fans a single envelope out to every
sink concurrently. ``now_ts`` returns the current wall-clock time as a
``google.protobuf.Timestamp``.

The proto stubs this module depends on are generated by issue #3; imports
are deferred so loading this module alone does not require the ``proto``
optional-dependency group.
"""

from __future__ import annotations

import asyncio
from typing import Any

# NOTE: EventSink is a protocol with an async ``emit(event_pb)`` method.
# We type it as ``Any`` here to avoid a circular dependency on the
# protocols module (issue #5). Runtime duck-typing is sufficient.


def now_ts() -> Any:
    """Return a ``google.protobuf.Timestamp`` pinned to the current time."""
    try:
        from google.protobuf.timestamp_pb2 import Timestamp
    except ModuleNotFoundError as exc:  # pragma: no cover
        raise ModuleNotFoundError(
            "google.protobuf is required for goldfive.events.now_ts(). "
            "Install the `proto` optional-dependency group."
        ) from exc
    ts = Timestamp()
    ts.GetCurrentTime()
    return ts


def _events_pb_module() -> Any:
    try:
        from goldfive.pb.goldfive.v1 import events_pb2
    except ModuleNotFoundError as exc:  # pragma: no cover
        raise ModuleNotFoundError(
            "goldfive protobuf stubs not available; generate them via "
            "`make proto` (requires the `proto` optional-dependency group) "
            "or install the package with the `proto` extra. See issue #3."
        ) from exc
    return events_pb2


def new_event(run_id: str, sequence: int) -> Any:
    """Build a fresh ``Event`` envelope with run_id/sequence/emitted_at set.

    The per-event payload (RunStarted, TaskCompleted, etc.) is assigned by
    the caller on the returned message's oneof field.
    """
    pb = _events_pb_module()
    evt = pb.Event()
    evt.run_id = run_id
    evt.sequence = sequence
    evt.emitted_at.CopyFrom(now_ts())
    return evt


async def emit(sinks: list[Any], event_pb: Any) -> None:
    """Fan ``event_pb`` out to every sink concurrently.

    Each sink's ``emit`` coroutine is awaited. Exceptions from individual
    sinks are collected via ``return_exceptions=True`` so one faulty sink
    cannot prevent others from observing the event. The first exception
    encountered is re-raised after all sinks have been awaited.
    """
    if not sinks:
        return
    results = await asyncio.gather(
        *(sink.emit(event_pb) for sink in sinks),
        return_exceptions=True,
    )
    for r in results:
        if isinstance(r, BaseException):
            raise r


def make_event(
    run_id: str,
    sequence: int,
    kind: str,
    payload: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Build a dict event envelope for callers that don't need the proto.

    Returns ``{run_id, sequence, kind, payload}``. Sinks type their
    ``emit`` argument as ``Any`` so both the proto envelope (from
    :func:`new_event`) and this dict envelope round-trip through the
    same fan-out machinery.
    """
    import time

    t = time.time_ns()
    return {
        "run_id": run_id,
        "sequence": sequence,
        "emitted_at": {"seconds": t // 1_000_000_000, "nanos": t % 1_000_000_000},
        "kind": kind,
        "payload": dict(payload or {}),
    }


# ---------------------------------------------------------------------------
# Typed event factories (proto path). Each returns a populated Event envelope
# with the appropriate oneof payload set. Callers produce one Event per call
# and pass it to :func:`emit` or a sink's ``emit`` directly.
#
# These helpers require the proto stubs; they raise ModuleNotFoundError if
# issue #3 hasn't generated them. Executors that need to run without proto
# should fall back to :func:`make_event`.
# ---------------------------------------------------------------------------


def run_started_event(
    run_id: str,
    sequence: int,
    goal_summary: str = "",
    started_at: Any | None = None,
) -> Any:
    evt = new_event(run_id, sequence)
    evt.run_started.run_id = run_id
    evt.run_started.goal_summary = goal_summary
    evt.run_started.started_at.CopyFrom(started_at or now_ts())
    return evt


def run_completed_event(run_id: str, sequence: int, outcome_summary: str = "") -> Any:
    evt = new_event(run_id, sequence)
    evt.run_completed.outcome_summary = outcome_summary
    return evt


def run_aborted_event(run_id: str, sequence: int, reason: str = "") -> Any:
    evt = new_event(run_id, sequence)
    evt.run_aborted.reason = reason
    return evt


def goal_derived_event(run_id: str, sequence: int, goals: list[Any]) -> Any:
    from goldfive.conv import to_pb_goal

    evt = new_event(run_id, sequence)
    for g in goals:
        evt.goal_derived.goals.add().CopyFrom(to_pb_goal(g))
    return evt


def plan_submitted_event(run_id: str, sequence: int, plan: Any) -> Any:
    from goldfive.conv import to_pb_plan

    evt = new_event(run_id, sequence)
    evt.plan_submitted.plan.CopyFrom(to_pb_plan(plan))
    return evt


def plan_revised_event(
    run_id: str,
    sequence: int,
    plan: Any,
    drift: Any | None = None,
    *,
    drift_kind: str = "",
    severity: str = "",
    reason: str = "",
    revision_index: int | None = None,
) -> Any:
    from goldfive.conv import to_pb_plan

    evt = new_event(run_id, sequence)
    evt.plan_revised.plan.CopyFrom(to_pb_plan(plan))

    if drift is not None:
        drift_kind = drift_kind or str(getattr(drift, "kind", ""))
        severity = severity or str(getattr(drift, "severity", ""))
        reason = reason or getattr(drift, "detail", "")

    if drift_kind:
        pb = _events_pb_module()
        try:
            normalized = drift_kind.upper() if not drift_kind.startswith("DRIFT_") else drift_kind
            evt.plan_revised.drift_kind = pb.DriftKind.Value(normalized)
        except (ValueError, AttributeError):
            pass
    if severity:
        pb = _events_pb_module()
        try:
            normalized = (
                severity.upper() if not severity.startswith("DRIFT_SEVERITY_") else severity
            )
            evt.plan_revised.severity = pb.DriftSeverity.Value(normalized)
        except (ValueError, AttributeError):
            pass
    evt.plan_revised.reason = reason
    evt.plan_revised.revision_index = int(
        revision_index if revision_index is not None else getattr(plan, "revision_index", 0)
    )
    return evt


def task_started_event(run_id: str, sequence: int, task_id: str, detail: str = "") -> Any:
    evt = new_event(run_id, sequence)
    evt.task_started.task_id = task_id
    evt.task_started.detail = detail
    return evt


def task_progress_event(
    run_id: str,
    sequence: int,
    task_id: str,
    fraction: float = 0.0,
    detail: str = "",
) -> Any:
    evt = new_event(run_id, sequence)
    evt.task_progress.task_id = task_id
    evt.task_progress.fraction = float(fraction)
    evt.task_progress.detail = detail
    return evt


def task_completed_event(
    run_id: str,
    sequence: int,
    task_id: str,
    summary: str = "",
    artifacts: dict[str, str] | None = None,
) -> Any:
    evt = new_event(run_id, sequence)
    evt.task_completed.task_id = task_id
    evt.task_completed.summary = summary
    for k, v in (artifacts or {}).items():
        evt.task_completed.artifacts[str(k)] = str(v)
    return evt


def task_failed_event(
    run_id: str,
    sequence: int,
    task_id: str,
    reason: str = "",
    recoverable: bool = True,
) -> Any:
    evt = new_event(run_id, sequence)
    evt.task_failed.task_id = task_id
    evt.task_failed.reason = reason
    evt.task_failed.recoverable = bool(recoverable)
    return evt


def task_blocked_event(
    run_id: str,
    sequence: int,
    task_id: str,
    blocker: str = "",
    needed: str = "",
) -> Any:
    evt = new_event(run_id, sequence)
    evt.task_blocked.task_id = task_id
    evt.task_blocked.blocker = blocker
    evt.task_blocked.needed = needed
    return evt


def task_cancelled_event(run_id: str, sequence: int, task_id: str, reason: str = "") -> Any:
    evt = new_event(run_id, sequence)
    evt.task_cancelled.task_id = task_id
    evt.task_cancelled.reason = reason
    return evt


def control_received_event(
    run_id: str,
    sequence: int,
    control_kind: Any,
    control_id: str,
) -> Any:
    """Build a ``DriftDetected`` envelope for a received ControlMessage.

    Phase 1 reuses the ``DriftDetected`` oneof (no proto regen). The mapping
    from :class:`goldfive.control.ControlKind` to :class:`DriftKind` is:
    ``PAUSE`` -> ``USER_PAUSE``, ``CANCEL`` -> ``USER_CANCEL``, everything
    else (``STEER``, ``RESUME``, ``REWIND_TO``) -> ``USER_STEER``. The raw
    control kind name is preserved in ``detail`` along with the control id
    so downstream consumers can disambiguate.
    """
    from goldfive.types import DriftEvent, DriftKind, DriftSeverity

    kind_name = str(getattr(control_kind, "value", control_kind)).upper()
    if kind_name == "PAUSE":
        drift_kind = DriftKind.USER_PAUSE
    elif kind_name == "CANCEL":
        drift_kind = DriftKind.USER_CANCEL
    else:
        drift_kind = DriftKind.USER_STEER

    drift = DriftEvent(
        kind=drift_kind,
        severity=DriftSeverity.WARNING,
        detail=f"control:{kind_name}:{control_id}",
    )
    return drift_detected_event(run_id, sequence, drift)


def conversation_started_event(
    run_id: str,
    sequence: int,
    conversation_id: str,
    started_at: Any | None = None,
) -> Any:
    """Build a ``ConversationStarted`` envelope.

    Emitted once per :class:`~goldfive.conversation.Conversation` on
    the first turn that uses it. ``run_id`` on the envelope carries
    the first turn's run id; the ``conversation_id`` field inside the
    payload is the stable identifier shared by every turn.
    """
    evt = new_event(run_id, sequence)
    evt.conversation_started.conversation_id = conversation_id
    evt.conversation_started.started_at.CopyFrom(started_at or now_ts())
    return evt


def conversation_ended_event(
    run_id: str,
    sequence: int,
    conversation_id: str,
    turn_count: int = 0,
    reason: str = "",
) -> Any:
    """Build a ``ConversationEnded`` envelope.

    Emitted when a caller resets the Runner's conversation (via
    :meth:`Runner.new_conversation`) or tears the Runner down. ``run_id``
    on the envelope is the last turn's run id so sinks can anchor the
    event in the run timeline.
    """
    evt = new_event(run_id, sequence)
    evt.conversation_ended.conversation_id = conversation_id
    evt.conversation_ended.turn_count = int(turn_count)
    evt.conversation_ended.reason = reason
    return evt


def approval_requested_event(
    run_id: str,
    sequence: int,
    *,
    target_id: str,
    kind: str,
    prompt: str = "",
    task_id: str = "",
    metadata: dict[str, str] | None = None,
) -> Any:
    """Build an ``ApprovalRequested`` envelope.

    ``kind`` is ``"task"`` (Flow A, `report_awaiting_approval`) or ``"tool"``
    (Flow B, ADK `require_confirmation=True`). ``target_id`` is what an
    incoming ``ControlMessage(APPROVE|REJECT)`` must quote back.
    """
    evt = new_event(run_id, sequence)
    evt.approval_requested.target_id = target_id
    evt.approval_requested.kind = kind
    evt.approval_requested.prompt = prompt
    evt.approval_requested.task_id = task_id
    for k, v in (metadata or {}).items():
        evt.approval_requested.metadata[str(k)] = str(v)
    return evt


def approval_granted_event(run_id: str, sequence: int, *, target_id: str, detail: str = "") -> Any:
    evt = new_event(run_id, sequence)
    evt.approval_granted.target_id = target_id
    evt.approval_granted.detail = detail
    return evt


def approval_rejected_event(run_id: str, sequence: int, *, target_id: str, detail: str = "") -> Any:
    evt = new_event(run_id, sequence)
    evt.approval_rejected.target_id = target_id
    evt.approval_rejected.detail = detail
    return evt


def agent_invocation_started_event(
    run_id: str,
    sequence: int,
    *,
    agent_name: str,
    task_id: str = "",
    invocation_id: str = "",
    parent_invocation_id: str = "",
    started_at: Any | None = None,
) -> Any:
    """Build an ``AgentInvocationStarted`` envelope.

    Emitted from the goldfive ADK plugin's ``before_run_callback`` — both
    on the top-level dispatch (goldfive's registry dispatch to the
    assignee's runner) and on any nested AgentTool-spawned sub-Runner.
    ``parent_invocation_id`` is empty for top-level and populated for
    nested invocations so sinks can reconstruct the delegation tree.
    """
    evt = new_event(run_id, sequence)
    evt.agent_invocation_started.agent_name = agent_name
    evt.agent_invocation_started.task_id = task_id
    evt.agent_invocation_started.invocation_id = invocation_id
    evt.agent_invocation_started.parent_invocation_id = parent_invocation_id
    evt.agent_invocation_started.started_at.CopyFrom(started_at or now_ts())
    return evt


def agent_invocation_completed_event(
    run_id: str,
    sequence: int,
    *,
    agent_name: str,
    task_id: str = "",
    invocation_id: str = "",
    summary: str = "",
    completed_at: Any | None = None,
) -> Any:
    """Build an ``AgentInvocationCompleted`` envelope.

    Paired with :func:`agent_invocation_started_event` — emitted from
    the plugin's ``after_run_callback`` when the runner finishes.
    ``summary`` is optional and may carry the final assistant text for
    sinks that render a timeline.
    """
    evt = new_event(run_id, sequence)
    evt.agent_invocation_completed.agent_name = agent_name
    evt.agent_invocation_completed.task_id = task_id
    evt.agent_invocation_completed.invocation_id = invocation_id
    evt.agent_invocation_completed.summary = summary
    evt.agent_invocation_completed.completed_at.CopyFrom(completed_at or now_ts())
    return evt


def delegation_observed_event(
    run_id: str,
    sequence: int,
    *,
    from_agent: str,
    to_agent: str,
    task_id: str = "",
    invocation_id: str = "",
    observed_at: Any | None = None,
) -> Any:
    """Build a ``DelegationObserved`` envelope.

    Emitted from the plugin's ``before_tool_callback`` when the tool is
    an ADK ``AgentTool`` — the host agent is about to delegate to the
    wrapped sub-agent. Observability only; the tool still runs.
    """
    evt = new_event(run_id, sequence)
    evt.delegation_observed.from_agent = from_agent
    evt.delegation_observed.to_agent = to_agent
    evt.delegation_observed.task_id = task_id
    evt.delegation_observed.invocation_id = invocation_id
    evt.delegation_observed.observed_at.CopyFrom(observed_at or now_ts())
    return evt


def build_plan_revision_diff(old_plan: Any, new_plan: Any) -> Any:
    """Build a ``PlanRevisionDiff`` pb comparing ``old_plan`` to ``new_plan``.

    Both arguments are :class:`goldfive.types.Plan` dataclasses (not pb
    messages). Either may be ``None`` — a ``None`` old plan treats every
    task/edge in ``new_plan`` as added, and vice versa — so this helper
    is safe to call even before the first revision.

    Identity rules (PLAN-LIFECYCLE.md §3.0):

    * Tasks are identified by ``id``. ``added_task_ids`` / ``removed_task_ids``
      are set difference on id sets. ``modified_task_ids`` is the id-
      intersection with at least one differing tracked metadata field
      (title, description, assignee_agent_id, status).
    * Edges are identified by the ``(from_task_id, to_task_id)`` pair.

    The returned message is a bare ``PlanRevisionDiff`` (not wrapped in
    an ``Event`` envelope). Callers splice it into
    ``plan_revised.diff.CopyFrom(...)`` themselves — this keeps the
    helper usable in tests without constructing a full envelope.
    """
    pb = _events_pb_module()
    diff = pb.PlanRevisionDiff()

    old_tasks = list(getattr(old_plan, "tasks", []) or []) if old_plan is not None else []
    new_tasks = list(getattr(new_plan, "tasks", []) or []) if new_plan is not None else []
    old_by_id = {t.id: t for t in old_tasks if getattr(t, "id", "")}
    new_by_id = {t.id: t for t in new_tasks if getattr(t, "id", "")}

    old_ids = set(old_by_id.keys())
    new_ids = set(new_by_id.keys())

    # Preserve the order tasks appear in new_plan / old_plan respectively —
    # sinks that render added-first, removed-next benefit from stable order
    # matching the authoritative plan layout.
    added = [t.id for t in new_tasks if t.id in (new_ids - old_ids)]
    removed = [t.id for t in old_tasks if t.id in (old_ids - new_ids)]
    modified: list[str] = []
    for tid in (t.id for t in new_tasks if t.id in (old_ids & new_ids)):
        old_t = old_by_id[tid]
        new_t = new_by_id[tid]
        if (
            getattr(old_t, "title", "") != getattr(new_t, "title", "")
            or getattr(old_t, "description", "") != getattr(new_t, "description", "")
            or getattr(old_t, "assignee_agent_id", "") != getattr(new_t, "assignee_agent_id", "")
            or str(getattr(old_t, "status", "")) != str(getattr(new_t, "status", ""))
        ):
            modified.append(tid)

    diff.added_task_ids.extend(added)
    diff.removed_task_ids.extend(removed)
    diff.modified_task_ids.extend(modified)

    def _edge_key(e: Any) -> tuple[str, str]:
        return (getattr(e, "from_task_id", ""), getattr(e, "to_task_id", ""))

    old_edges = list(getattr(old_plan, "edges", []) or []) if old_plan is not None else []
    new_edges = list(getattr(new_plan, "edges", []) or []) if new_plan is not None else []
    old_edge_keys = {_edge_key(e) for e in old_edges}
    new_edge_keys = {_edge_key(e) for e in new_edges}

    from goldfive.pb.goldfive.v1 import types_pb2

    for e in new_edges:
        if _edge_key(e) not in old_edge_keys:
            diff.added_edges.append(
                types_pb2.TaskEdge(from_task_id=e.from_task_id, to_task_id=e.to_task_id)
            )
    for e in old_edges:
        if _edge_key(e) not in new_edge_keys:
            diff.removed_edges.append(
                types_pb2.TaskEdge(from_task_id=e.from_task_id, to_task_id=e.to_task_id)
            )
    return diff


def drift_detected_event(run_id: str, sequence: int, drift: Any) -> Any:
    pb = _events_pb_module()
    evt = new_event(run_id, sequence)
    kind_name = str(getattr(drift, "kind", ""))
    sev_name = str(getattr(drift, "severity", ""))
    if kind_name:
        try:
            evt.drift_detected.kind = pb.DriftKind.Value(
                kind_name.upper() if not kind_name.startswith("DRIFT_") else kind_name
            )
        except (ValueError, AttributeError):
            pass
    if sev_name:
        try:
            evt.drift_detected.severity = pb.DriftSeverity.Value(
                sev_name.upper() if not sev_name.startswith("DRIFT_SEVERITY_") else sev_name
            )
        except (ValueError, AttributeError):
            pass
    evt.drift_detected.detail = getattr(drift, "detail", "")
    evt.drift_detected.current_task_id = getattr(drift, "current_task_id", "")
    evt.drift_detected.current_agent_id = getattr(drift, "current_agent_id", "")
    return evt
