"""Event envelope helpers.

``new_event`` constructs a fresh ``Event`` pb with ``run_id``, ``sequence``
and ``emitted_at`` populated. ``emit`` fans a single envelope out to every
sink concurrently. ``now_ts`` returns the current wall-clock time as a
``google.protobuf.Timestamp``.

The proto stubs this module depends on are generated by issue #3; imports
are deferred so loading this module alone does not require the ``proto``
optional-dependency group.
"""

from __future__ import annotations

import asyncio
from typing import Any

# NOTE: EventSink is a protocol with an async ``emit(event_pb)`` method.
# We type it as ``Any`` here to avoid a circular dependency on the
# protocols module (issue #5). Runtime duck-typing is sufficient.


def now_ts() -> Any:
    """Return a ``google.protobuf.Timestamp`` pinned to the current time."""
    try:
        from google.protobuf.timestamp_pb2 import Timestamp
    except ModuleNotFoundError as exc:  # pragma: no cover
        raise ModuleNotFoundError(
            "google.protobuf is required for goldfive.events.now_ts(). "
            "Install the `proto` optional-dependency group."
        ) from exc
    ts = Timestamp()
    ts.GetCurrentTime()
    return ts


def _events_pb_module() -> Any:
    try:
        from goldfive.pb.goldfive.v1 import events_pb2
    except ModuleNotFoundError as exc:  # pragma: no cover
        raise ModuleNotFoundError(
            "goldfive protobuf stubs not available; generate them via "
            "`make proto` (requires the `proto` optional-dependency group) "
            "or install the package with the `proto` extra. See issue #3."
        ) from exc
    return events_pb2


def new_event(run_id: str, sequence: int) -> Any:
    """Build a fresh ``Event`` envelope with run_id/sequence/emitted_at set.

    The per-event payload (RunStarted, TaskCompleted, etc.) is assigned by
    the caller on the returned message's oneof field.
    """
    pb = _events_pb_module()
    evt = pb.Event()
    evt.run_id = run_id
    evt.sequence = sequence
    evt.emitted_at.CopyFrom(now_ts())
    return evt


async def emit(sinks: list[Any], event_pb: Any) -> None:
    """Fan ``event_pb`` out to every sink concurrently.

    Each sink's ``emit`` coroutine is awaited. Exceptions from individual
    sinks are collected via ``return_exceptions=True`` so one faulty sink
    cannot prevent others from observing the event. The first exception
    encountered is re-raised after all sinks have been awaited.
    """
    if not sinks:
        return
    results = await asyncio.gather(
        *(sink.emit(event_pb) for sink in sinks),
        return_exceptions=True,
    )
    for r in results:
        if isinstance(r, BaseException):
            raise r


def make_event(
    run_id: str,
    sequence: int,
    kind: str,
    payload: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Build a dict event envelope for callers that don't need the proto.

    Returns ``{run_id, sequence, kind, payload}``. Sinks type their
    ``emit`` argument as ``Any`` so both the proto envelope (from
    :func:`new_event`) and this dict envelope round-trip through the
    same fan-out machinery.
    """
    import time

    t = time.time_ns()
    return {
        "run_id": run_id,
        "sequence": sequence,
        "emitted_at": {"seconds": t // 1_000_000_000, "nanos": t % 1_000_000_000},
        "kind": kind,
        "payload": dict(payload or {}),
    }


# ---------------------------------------------------------------------------
# Typed event factories (proto path). Each returns a populated Event envelope
# with the appropriate oneof payload set. Callers produce one Event per call
# and pass it to :func:`emit` or a sink's ``emit`` directly.
#
# These helpers require the proto stubs; they raise ModuleNotFoundError if
# issue #3 hasn't generated them. Executors that need to run without proto
# should fall back to :func:`make_event`.
# ---------------------------------------------------------------------------


def run_started_event(
    run_id: str,
    sequence: int,
    goal_summary: str = "",
    started_at: Any | None = None,
) -> Any:
    evt = new_event(run_id, sequence)
    evt.run_started.run_id = run_id
    evt.run_started.goal_summary = goal_summary
    evt.run_started.started_at.CopyFrom(started_at or now_ts())
    return evt


def run_completed_event(run_id: str, sequence: int, outcome_summary: str = "") -> Any:
    evt = new_event(run_id, sequence)
    evt.run_completed.outcome_summary = outcome_summary
    return evt


def run_aborted_event(run_id: str, sequence: int, reason: str = "") -> Any:
    evt = new_event(run_id, sequence)
    evt.run_aborted.reason = reason
    return evt


def goal_derived_event(run_id: str, sequence: int, goals: list[Any]) -> Any:
    from goldfive.conv import to_pb_goal

    evt = new_event(run_id, sequence)
    for g in goals:
        evt.goal_derived.goals.add().CopyFrom(to_pb_goal(g))
    return evt


def plan_submitted_event(run_id: str, sequence: int, plan: Any) -> Any:
    from goldfive.conv import to_pb_plan

    evt = new_event(run_id, sequence)
    evt.plan_submitted.plan.CopyFrom(to_pb_plan(plan))
    return evt


def plan_revised_event(
    run_id: str,
    sequence: int,
    plan: Any,
    drift: Any | None = None,
    *,
    drift_kind: str = "",
    severity: str = "",
    reason: str = "",
    revision_index: int | None = None,
) -> Any:
    from goldfive.conv import to_pb_plan

    evt = new_event(run_id, sequence)
    evt.plan_revised.plan.CopyFrom(to_pb_plan(plan))

    if drift is not None:
        drift_kind = drift_kind or str(getattr(drift, "kind", ""))
        severity = severity or str(getattr(drift, "severity", ""))
        reason = reason or getattr(drift, "detail", "")

    if drift_kind:
        pb = _events_pb_module()
        try:
            normalized = drift_kind.upper() if not drift_kind.startswith("DRIFT_") else drift_kind
            evt.plan_revised.drift_kind = pb.DriftKind.Value(normalized)
        except (ValueError, AttributeError):
            pass
    if severity:
        pb = _events_pb_module()
        try:
            normalized = (
                severity.upper() if not severity.startswith("DRIFT_SEVERITY_") else severity
            )
            evt.plan_revised.severity = pb.DriftSeverity.Value(normalized)
        except (ValueError, AttributeError):
            pass
    evt.plan_revised.reason = reason
    evt.plan_revised.revision_index = int(
        revision_index if revision_index is not None else getattr(plan, "revision_index", 0)
    )
    return evt


def task_started_event(run_id: str, sequence: int, task_id: str, detail: str = "") -> Any:
    evt = new_event(run_id, sequence)
    evt.task_started.task_id = task_id
    evt.task_started.detail = detail
    return evt


def task_progress_event(
    run_id: str,
    sequence: int,
    task_id: str,
    fraction: float = 0.0,
    detail: str = "",
) -> Any:
    evt = new_event(run_id, sequence)
    evt.task_progress.task_id = task_id
    evt.task_progress.fraction = float(fraction)
    evt.task_progress.detail = detail
    return evt


def task_completed_event(
    run_id: str,
    sequence: int,
    task_id: str,
    summary: str = "",
    artifacts: dict[str, str] | None = None,
) -> Any:
    evt = new_event(run_id, sequence)
    evt.task_completed.task_id = task_id
    evt.task_completed.summary = summary
    for k, v in (artifacts or {}).items():
        evt.task_completed.artifacts[str(k)] = str(v)
    return evt


def task_failed_event(
    run_id: str,
    sequence: int,
    task_id: str,
    reason: str = "",
    recoverable: bool = True,
) -> Any:
    evt = new_event(run_id, sequence)
    evt.task_failed.task_id = task_id
    evt.task_failed.reason = reason
    evt.task_failed.recoverable = bool(recoverable)
    return evt


def task_blocked_event(
    run_id: str,
    sequence: int,
    task_id: str,
    blocker: str = "",
    needed: str = "",
) -> Any:
    evt = new_event(run_id, sequence)
    evt.task_blocked.task_id = task_id
    evt.task_blocked.blocker = blocker
    evt.task_blocked.needed = needed
    return evt


def task_cancelled_event(run_id: str, sequence: int, task_id: str, reason: str = "") -> Any:
    evt = new_event(run_id, sequence)
    evt.task_cancelled.task_id = task_id
    evt.task_cancelled.reason = reason
    return evt


def control_received_event(
    run_id: str,
    sequence: int,
    control_kind: Any,
    control_id: str,
) -> Any:
    """Build a ``DriftDetected`` envelope for a received ControlMessage.

    Phase 1 reuses the ``DriftDetected`` oneof (no proto regen). The mapping
    from :class:`goldfive.control.ControlKind` to :class:`DriftKind` is:
    ``PAUSE`` -> ``USER_PAUSE``, ``CANCEL`` -> ``USER_CANCEL``, everything
    else (``STEER``, ``RESUME``, ``REWIND_TO``) -> ``USER_STEER``. The raw
    control kind name is preserved in ``detail`` along with the control id
    so downstream consumers can disambiguate.
    """
    from goldfive.types import DriftEvent, DriftKind, DriftSeverity

    kind_name = str(getattr(control_kind, "value", control_kind)).upper()
    if kind_name == "PAUSE":
        drift_kind = DriftKind.USER_PAUSE
    elif kind_name == "CANCEL":
        drift_kind = DriftKind.USER_CANCEL
    else:
        drift_kind = DriftKind.USER_STEER

    drift = DriftEvent(
        kind=drift_kind,
        severity=DriftSeverity.WARNING,
        detail=f"control:{kind_name}:{control_id}",
    )
    return drift_detected_event(run_id, sequence, drift)


def drift_detected_event(run_id: str, sequence: int, drift: Any) -> Any:
    pb = _events_pb_module()
    evt = new_event(run_id, sequence)
    kind_name = str(getattr(drift, "kind", ""))
    sev_name = str(getattr(drift, "severity", ""))
    if kind_name:
        try:
            evt.drift_detected.kind = pb.DriftKind.Value(
                kind_name.upper() if not kind_name.startswith("DRIFT_") else kind_name
            )
        except (ValueError, AttributeError):
            pass
    if sev_name:
        try:
            evt.drift_detected.severity = pb.DriftSeverity.Value(
                sev_name.upper() if not sev_name.startswith("DRIFT_SEVERITY_") else sev_name
            )
        except (ValueError, AttributeError):
            pass
    evt.drift_detected.detail = getattr(drift, "detail", "")
    evt.drift_detected.current_task_id = getattr(drift, "current_task_id", "")
    evt.drift_detected.current_agent_id = getattr(drift, "current_agent_id", "")
    return evt
