"""Event envelope helpers.

``new_event`` constructs a fresh ``Event`` pb with ``run_id``, ``sequence``
and ``emitted_at`` populated. ``emit`` fans a single envelope out to every
sink concurrently. ``now_ts`` returns the current wall-clock time as a
``google.protobuf.Timestamp``.

The proto stubs this module depends on are generated by issue #3; imports
are deferred so loading this module alone does not require the ``proto``
optional-dependency group.
"""

from __future__ import annotations

import asyncio
from typing import Any

# NOTE: EventSink is a protocol with an async ``emit(event_pb)`` method.
# We type it as ``Any`` here to avoid a circular dependency on the
# protocols module (issue #5). Runtime duck-typing is sufficient.


def now_ts() -> Any:
    """Return a ``google.protobuf.Timestamp`` pinned to the current time."""
    try:
        from google.protobuf.timestamp_pb2 import Timestamp
    except ModuleNotFoundError as exc:  # pragma: no cover
        raise ModuleNotFoundError(
            "google.protobuf is required for goldfive.events.now_ts(). "
            "Install the `proto` optional-dependency group."
        ) from exc
    ts = Timestamp()
    ts.GetCurrentTime()
    return ts


def _events_pb_module() -> Any:
    try:
        from goldfive.pb.goldfive.v1 import events_pb2
    except ModuleNotFoundError as exc:  # pragma: no cover
        raise ModuleNotFoundError(
            "goldfive protobuf stubs not available; generate them via "
            "`make proto` (requires the `proto` optional-dependency group) "
            "or install the package with the `proto` extra. See issue #3."
        ) from exc
    return events_pb2


def new_event(run_id: str, sequence: int) -> Any:
    """Build a fresh ``Event`` envelope with run_id/sequence/emitted_at set.

    The per-event payload (RunStarted, TaskCompleted, etc.) is assigned by
    the caller on the returned message's oneof field.
    """
    pb = _events_pb_module()
    evt = pb.Event()
    evt.run_id = run_id
    evt.sequence = sequence
    evt.emitted_at.CopyFrom(now_ts())
    return evt


async def emit(sinks: list[Any], event_pb: Any) -> None:
    """Fan ``event_pb`` out to every sink concurrently.

    Each sink's ``emit`` coroutine is awaited. Exceptions from individual
    sinks are collected via ``return_exceptions=True`` so one faulty sink
    cannot prevent others from observing the event. The first exception
    encountered is re-raised after all sinks have been awaited.
    """
    if not sinks:
        return
    results = await asyncio.gather(
        *(sink.emit(event_pb) for sink in sinks),
        return_exceptions=True,
    )
    for r in results:
        if isinstance(r, BaseException):
            raise r


def make_event(
    run_id: str,
    sequence: int,
    kind: str,
    payload: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Build a dict event envelope for callers that don't need the proto.

    Returns ``{run_id, sequence, kind, payload}``. Sinks type their
    ``emit`` argument as ``Any`` so both the proto envelope (from
    :func:`new_event`) and this dict envelope round-trip through the
    same fan-out machinery.
    """
    import time

    t = time.time_ns()
    return {
        "run_id": run_id,
        "sequence": sequence,
        "emitted_at": {"seconds": t // 1_000_000_000, "nanos": t % 1_000_000_000},
        "kind": kind,
        "payload": dict(payload or {}),
    }
