# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: goldfive/v1/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'goldfive/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from goldfive.v1 import events_pb2 as goldfive_dot_v1_dot_events__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19goldfive/v1/service.proto\x12\x0bgoldfive.v1\x1a\x18goldfive/v1/events.proto\"7\n\x14StreamEventsResponse\x12\x10\n\x08received\x18\x01 \x01(\x04\x12\r\n\x05\x65rror\x18\x02 \x01(\t2Z\n\x0fGoldfiveIngress\x12G\n\x0cStreamEvents\x12\x12.goldfive.v1.Event\x1a!.goldfive.v1.StreamEventsResponse(\x01\x42\x39Z7github.com/pedapudi/goldfive/gen/goldfive/v1;goldfivev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'goldfive.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/pedapudi/goldfive/gen/goldfive/v1;goldfivev1'
  _globals['_STREAMEVENTSRESPONSE']._serialized_start=68
  _globals['_STREAMEVENTSRESPONSE']._serialized_end=123
  _globals['_GOLDFIVEINGRESS']._serialized_start=125
  _globals['_GOLDFIVEINGRESS']._serialized_end=215
# @@protoc_insertion_point(module_scope)
