# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from goldfive.v1 import events_pb2 as goldfive_dot_v1_dot_events__pb2
from goldfive.v1 import service_pb2 as goldfive_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in goldfive/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GoldfiveIngressStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamEvents = channel.stream_unary(
                '/goldfive.v1.GoldfiveIngress/StreamEvents',
                request_serializer=goldfive_dot_v1_dot_events__pb2.Event.SerializeToString,
                response_deserializer=goldfive_dot_v1_dot_service__pb2.StreamEventsResponse.FromString,
                _registered_method=True)


class GoldfiveIngressServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamEvents(self, request_iterator, context):
        """Client streams Events; server returns a single summary after the
        client half-closes. Implementations fan events out to local
        EventSinks in order.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GoldfiveIngressServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamEvents': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=goldfive_dot_v1_dot_events__pb2.Event.FromString,
                    response_serializer=goldfive_dot_v1_dot_service__pb2.StreamEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'goldfive.v1.GoldfiveIngress', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('goldfive.v1.GoldfiveIngress', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GoldfiveIngress(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/goldfive.v1.GoldfiveIngress/StreamEvents',
            goldfive_dot_v1_dot_events__pb2.Event.SerializeToString,
            goldfive_dot_v1_dot_service__pb2.StreamEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
